#!/usr/bin/env python
print "importing libraries"

import rosbag
import rospy
from sensor_msgs.msg import Image
from sensor_msgs.msg import Imu
import ImageFile
import time, sys, os
import argparse
import cv2
import numpy as np
import csv
import pickle
import math

#structure
# dataset/cam0/TIMESTAMP.png
# dataset/camN/TIMESTAMP.png
# dataset/imu.csv

#setup the argument list
parser = argparse.ArgumentParser(description='Create a ROS bag using the images and imu data.')
parser.add_argument('--mov',  metavar='folder', nargs='?', help='Data folder')
parser.add_argument('--acc',  metavar='folder', nargs='?', help='Data folder')
parser.add_argument('--time',  metavar='folder', nargs='?', help='Data folder')
parser.add_argument('--output-bag', metavar='output_bag',  default="output.bag", help='ROS bag file %(default)s')
parser.add_argument('--side', metavar='output_bag',  help='ROS bag file %(default)s')

#print help if no argument is specified
if len(sys.argv)<2:
    parser.print_help()
    sys.exit(0)

#parse the args
parsed = parser.parse_args()

def getImageFilesFromDir(dir):
    '''Generates a list of files from the directory'''
    image_files = list()
    timestamps = list()
    if os.path.exists(dir):
        for path, names, files in os.walk(dir):
            for f in files:
                if os.path.splitext(f)[1] in ['.bmp', '.png', '.jpg']:
                    image_files.append( os.path.join( path, f ) )
                    timestamps.append(os.path.splitext(f)[0]) 
    #sort by timestamp
    sort_list = sorted(zip(timestamps, image_files))
    image_files = [file[1] for file in sort_list]
    return image_files

def getCamFoldersFromDir(dir):
    '''Generates a list of all folders that start with cam e.g. cam0'''
    cam_folders = list()
    if os.path.exists(dir):
        for path, folders, files in os.walk(dir):
            for folder in folders:                
                if folder[0:3] == "cam":
                    cam_folders.append(folder)
    return cam_folders

def getImuCsvFiles(dir):
    '''Generates a list of all csv files that start with imu'''
    imu_files = list()
    if os.path.exists(dir):
        for path, folders, files in os.walk(dir):
            for file in files:
                if file[0:3] == 'imu' and os.path.splitext(file)[1] == ".csv":
                    imu_files.append( os.path.join( path, file ) )
    
    return imu_files

def loadImageToRosMsg(filename):
    image_np = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)
    
    timestamp_nsecs = os.path.splitext(os.path.basename(filename))[0]
    timestamp = rospy.Time( secs=int(timestamp_nsecs[0:-9]), nsecs=int(timestamp_nsecs[-9:]) )

    rosimage = Image()
    rosimage.header.stamp = timestamp
    rosimage.height = image_np.shape[0]
    rosimage.width = image_np.shape[1]
    rosimage.step = rosimage.width  #only with mono8! (step = width * byteperpixel * numChannels)
    rosimage.encoding = "mono8"
    rosimage.data = image_np.tostring()
    
    return rosimage, timestamp
    
def loadImageDataToRosMsg(image_np, timestamp_nsec):
    usec = np.modf(timestamp_nsec)[0] * 1e6
    timestamp = rospy.Time( secs=int(timestamp_nsec), nsecs=int(usec) )

    rosimage = Image()
    rosimage.header.stamp = timestamp
    rosimage.height = image_np.shape[0]
    rosimage.width = image_np.shape[1]
    rosimage.step = rosimage.width  #only with mono8! (step = width * byteperpixel * numChannels)
    rosimage.encoding = "mono8"
    rosimage.data = image_np.tostring()
    
    return rosimage, timestamp

def createImuMessge(timestamp_int, omega, alpha):
    timestamp_nsecs = str(timestamp_int)
    timestamp = rospy.Time( int(timestamp_nsecs[0:-9]), int(timestamp_nsecs[-9:]) )
    
    rosimu = Imu()
    rosimu.header.stamp = timestamp
    rosimu.angular_velocity.x = float(omega[0])
    rosimu.angular_velocity.y = float(omega[1])
    rosimu.angular_velocity.z = float(omega[2])
    rosimu.linear_acceleration.x = float(alpha[0])
    rosimu.linear_acceleration.y = float(alpha[1])
    rosimu.linear_acceleration.z = float(alpha[2])
    
    return rosimu, timestamp
    
def createImuDataMessge(timestamp_nsec, omega, alpha):
    usec = math.modf(timestamp_nsec)[0] * 1e6
    timestamp = rospy.Time( secs=int(timestamp_nsec), nsecs=int(usec) )
    
    rosimu = Imu()
    rosimu.header.stamp = timestamp
    rosimu.angular_velocity.x = float(omega[0])
    rosimu.angular_velocity.y = float(omega[1])
    rosimu.angular_velocity.z = float(omega[2])
    rosimu.linear_acceleration.x = float(alpha[0])
    rosimu.linear_acceleration.y = float(alpha[1])
    rosimu.linear_acceleration.z = float(alpha[2])
    
    return rosimu, timestamp


#create the bag
try:
    bag = rosbag.Bag(parsed.output_bag, 'w')

    topic = "cam0"

    #time stamp
    time_file = parsed.time
    time_list = np.loadtxt(time_file)

    #write images
    mov_file = parsed.mov
    video = cv2.VideoCapture(mov_file)
    cnt = 0
    while video.isOpened():
        ret, image = video.read()
        if ret is False:
            break
        timestamp_msec = time_list[cnt]
        cnt += 1

        if image.shape[2] == 3:
            image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

        # roi setting
        if parsed.side == "left":
            roi = [0, image.shape[0], 0, image.shape[1]//2]
        elif parsed.side == "right":
            roi = [0, image.shape[0], image.shape[1]//2, image.shape[1]]
        
        image = image[roi[0]:roi[1], roi[2]:roi[3], ...]
            
        image_msg, timestamp = loadImageDataToRosMsg(image, timestamp_msec)
        bag.write("/{0}/image_raw".format(topic), image_msg, timestamp)

    #write imu data
    imu_file = parsed.acc
    acc_list = np.loadtxt(imu_file, delimiter=',')

    for i, (timestamp_msec, acc) in enumerate(zip(time_list, acc_list)):
        ax, ay, az, gx, gy, gz = acc
        
        imumsg, timestamp = createImuDataMessge(timestamp_msec, [ax,ay,az], [gx,gy,gz])
        bag.write("/{0}".format(topic), imumsg, timestamp)
        # bag.write("/{0}/imu".format(topic), imumsg, timestamp)
finally:
    bag.close()

